### ISSUE TITLE
secUid error returned. Can you add more documentation please on project setup!

### ISSUE THREAD

**Issue by AliKhyar** [0aub/tiktok-bulk-downloader#1]
```powershell
user@host: tiktok-bulk-downloader$ python tiktok_dl.py --username @darwin --generate
[INFO]:  Generating json data...
Traceback (most recent call last):
  File "tiktok_dl.py", line 376, in <module>
    main(args)
  File "tiktok_dl.py", line 358, in main
    generate_data()
  File "tiktok_dl.py", line 238, in generate_data
    posts = get_posts()
  File "tiktok_dl.py", line 204, in get_posts
    update_user()
  File "tiktok_dl.py", line 195, in update_user
    PARAMS["secUid"] = response["userInfo"]["user"]["secUid"]
KeyError: 'secUid'
```

**Comment by 0aub** [comment]
Try to use it without @

**Comment by 0aub** [comment]
Also, thank you. I should handle the errors with clear messages.

**Comment by 0aub** [comment]
hello Ali,

this command will work with you:
```
python tiktok_dl.py --username darwin --generate
```

I tested it  👍

**Comment by AliKhyar** [comment]
@0aub Thanks it worked. The video part that didn't work, I just bandaid-ed your code with another one so it can work.
