### ISSUE TITLE
It doesn't seem to work anymore, at least not on my system

### ISSUE THREAD

**Issue by korewatori** [0aub/tiktok-bulk-downloader#3]
I had used this once before and it worked flawlessly but then tried later on a few days later and it didn't work, instead giving me this. Ignore the user I tried it on, just did that for shits and giggles.

```
[INFO]:  Generating json data...
Traceback (most recent call last):
  File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 176, in update_user
    PARAMS['secUid'] = response['userInfo']['user']['secUid']
KeyError: 'userInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 440, in <module>
    main(args)
  File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 424, in main
    generate_data()
  File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 223, in generate_data
    messy_posts = get_posts()
  File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 191, in get_posts
    update_user()
  File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 181, in update_user
    raise Exception(f'''
Exception:
        We could not find data about 10downingstreet.
        Take a look to these tips and try again.
          - Do not add @ in the beginning of the username
          - This script does not accept private accounts yet
```

**Comment by korewatori** [comment]
> I had used this once before and it worked flawlessly but then tried later on a few days later and it didn't work, instead giving me this. Ignore the user I tried it on, just did that for shits and giggles.
> 
> ```
> [INFO]:  Generating json data...
> Traceback (most recent call last):
>   File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 176, in update_user
>     PARAMS['secUid'] = response['userInfo']['user']['secUid']
> KeyError: 'userInfo'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 440, in <module>
>     main(args)
>   File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 424, in main
>     generate_data()
>   File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 223, in generate_data
>     messy_posts = get_posts()
>   File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 191, in get_posts
>     update_user()
>   File "C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py", line 181, in update_user
>     raise Exception(f'''
> Exception:
>         We could not find data about 10downingstreet.
>         Take a look to these tips and try again.
>           - Do not add @ in the beginning of the username
>           - This script does not accept private accounts yet
> ```

for what it's worth I'm trying to run the script on Python 3.10.4 which is not currently in my PATH, so I ran it using `C:\Python\Python310\python.exe C:\Users\Tori\Downloads\tiktok-bulk-downloader-main\tiktok_dl.py` in cmd

**Comment by 0aub** [comment]
Good evening korewatori,

I'm sorry for being late on the response. The above exception was raised after extracting the user's secret id directly from one of TikTok APIs. So, the problem here is just a failed request to that API. I thought the user is private or you misspelled it. Unfortunately, the user's account is public and you typed it without mistakes. The remaining causes are the API endpoint and the request parameters. Maybe they changed their API endpoint or blocked our token parameter.


Anyway, I'll fix that and updates you when it's ready.

**Comment by github-userx** [comment]
@0aub Did you fix it already? apparently tiktok changed lots with their api?

Yt-dlp has big issue with user feeds as well, maybe you can help with your knowledge:  https://github.com/yt-dlp/yt-dlp/issues/3776
