### ISSUE TITLE
How can I fix this issue 

### ISSUE THREAD

**Issue by Harshit-shrivastav** [0aub/tiktok-bulk-downloader#9]
(venv) root@cloud-standard-nl-2-5234432:~/tt# python tiktok_dl.py --username darwin --generate
[INFO]:  Generating json data...
Traceback (most recent call last):
  File "/root/tt/tiktok_dl.py", line 175, in update_user
    response = tiktok_request(path, x_tt_params=None)
  File "/root/tt/tiktok_dl.py", line 163, in tiktok_request
    return json.loads(requests.get(url, headers=headers).text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char
0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/tt/tiktok_dl.py", line 440, in <module>
    main(args)
  File "/root/tt/tiktok_dl.py", line 424, in main
    generate_data()
  File "/root/tt/tiktok_dl.py", line 223, in generate_data
    messy_posts = get_posts()
  File "/root/tt/tiktok_dl.py", line 191, in get_posts
    update_user()
  File "/root/tt/tiktok_dl.py", line 181, in update_user
    raise Exception(f'''
Exception:
        We could not find data about darwin.
        Take a look to these tips and try again.
          - Do not add @ in the beginning of the username
          - This script does not accept private accounts yet
(venv) root@cloud-standard-nl-2-5234432:~/tt#

**Comment by Harshit-shrivastav** [comment]
`(venv) root@cloud-standard-nl-2-5234432:~/tt# python tiktok_dl.py --username darwin --generate
[INFO]:  Generating json data...
Traceback (most recent call last):
  File "/root/tt/tiktok_dl.py", line 175, in update_user
    response = tiktok_request(path, x_tt_params=None)
  File "/root/tt/tiktok_dl.py", line 163, in tiktok_request
    return json.loads(requests.get(url, headers=headers).text)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char
0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/tt/tiktok_dl.py", line 440, in <module>
    main(args)
  File "/root/tt/tiktok_dl.py", line 424, in main
    generate_data()
  File "/root/tt/tiktok_dl.py", line 223, in generate_data
    messy_posts = get_posts()
  File "/root/tt/tiktok_dl.py", line 191, in get_posts
    update_user()
  File "/root/tt/tiktok_dl.py", line 181, in update_user
    raise Exception(f'''
Exception:
        We could not find data about darwin.
        Take a look to these tips and try again.
          - Do not add @ in the beginning of the username
          - This script does not accept private accounts yet
(venv) root@cloud-standard-nl-2-5234432:~/tt#`
